development:
  adapter: postgresql
  enconding: utf8
  database: d154doskp7cre1
  username: agvzbtslloluki
  password: sKooPfmrtcGpXQnCo8x18sMrqo
  host: ec2-54-235-152-226.compute-1.amazonaws.com
  port: 5432


